package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AlunoEnderecoId generated by hbm2java
 */
@Embeddable
public class AlunoEnderecoId implements java.io.Serializable {

	private static final long serialVersionUID = 7671542334992299838L;
	private int indAluno;
	private String indEndereco;

	public AlunoEnderecoId() {
	}

	public AlunoEnderecoId(int indAluno, String indEndereco) {
		this.indAluno = indAluno;
		this.indEndereco = indEndereco;
	}

	@Column(name = "ind_aluno", nullable = false)
	@NotNull
	public int getIndAluno() {
		return this.indAluno;
	}

	public void setIndAluno(int indAluno) {
		this.indAluno = indAluno;
	}

	@Column(name = "ind_endereco", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getIndEndereco() {
		return this.indEndereco;
	}

	public void setIndEndereco(String indEndereco) {
		this.indEndereco = indEndereco;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlunoEnderecoId))
			return false;
		AlunoEnderecoId castOther = (AlunoEnderecoId) other;

		return (this.getIndAluno() == castOther.getIndAluno())
				&& ((this.getIndEndereco() == castOther.getIndEndereco()) || (this
						.getIndEndereco() != null
						&& castOther.getIndEndereco() != null && this
						.getIndEndereco().equals(castOther.getIndEndereco())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIndAluno();
		result = 37
				* result
				+ (getIndEndereco() == null ? 0 : this.getIndEndereco()
						.hashCode());
		return result;
	}

}
