package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AvaliacaoId generated by hbm2java
 */
@Embeddable
public class AvaliacaoId implements java.io.Serializable {

	private static final long serialVersionUID = 8385639963385945040L;
	private int idtAvaliacao;
	private String codAvaliacao;
	private int indTurma;
	private int indAluno;
	private int indDisciplina;

	public AvaliacaoId() {
	}

	public AvaliacaoId(int idtAvaliacao, String codAvaliacao, int indTurma,
			int indAluno, int indDisciplina) {
		this.idtAvaliacao = idtAvaliacao;
		this.codAvaliacao = codAvaliacao;
		this.indTurma = indTurma;
		this.indAluno = indAluno;
		this.indDisciplina = indDisciplina;
	}

	@Column(name = "idt_avaliacao", nullable = false)
	@NotNull
	public int getIdtAvaliacao() {
		return this.idtAvaliacao;
	}

	public void setIdtAvaliacao(int idtAvaliacao) {
		this.idtAvaliacao = idtAvaliacao;
	}

	@Column(name = "cod_avaliacao", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getCodAvaliacao() {
		return this.codAvaliacao;
	}

	public void setCodAvaliacao(String codAvaliacao) {
		this.codAvaliacao = codAvaliacao;
	}

	@Column(name = "ind_turma", nullable = false)
	@NotNull
	public int getIndTurma() {
		return this.indTurma;
	}

	public void setIndTurma(int indTurma) {
		this.indTurma = indTurma;
	}

	@Column(name = "ind_aluno", nullable = false)
	@NotNull
	public int getIndAluno() {
		return this.indAluno;
	}

	public void setIndAluno(int indAluno) {
		this.indAluno = indAluno;
	}

	@Column(name = "ind_disciplina", nullable = false)
	@NotNull
	public int getIndDisciplina() {
		return this.indDisciplina;
	}

	public void setIndDisciplina(int indDisciplina) {
		this.indDisciplina = indDisciplina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvaliacaoId))
			return false;
		AvaliacaoId castOther = (AvaliacaoId) other;

		return (this.getIdtAvaliacao() == castOther.getIdtAvaliacao())
				&& ((this.getCodAvaliacao() == castOther.getCodAvaliacao()) || (this
						.getCodAvaliacao() != null
						&& castOther.getCodAvaliacao() != null && this
						.getCodAvaliacao().equals(castOther.getCodAvaliacao())))
				&& (this.getIndTurma() == castOther.getIndTurma())
				&& (this.getIndAluno() == castOther.getIndAluno())
				&& (this.getIndDisciplina() == castOther.getIndDisciplina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdtAvaliacao();
		result = 37
				* result
				+ (getCodAvaliacao() == null ? 0 : this.getCodAvaliacao()
						.hashCode());
		result = 37 * result + this.getIndTurma();
		result = 37 * result + this.getIndAluno();
		result = 37 * result + this.getIndDisciplina();
		return result;
	}

}
