package br.inf.prismasoft.academix.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * HistoricoItem generated by hbm2java
 */
@Entity
@Table(name = "HISTORICO_ITEM", schema = "ACADEMIX")
public class HistoricoItem implements java.io.Serializable {

	private static final long serialVersionUID = 4916265507492094000L;
	private HistoricoItemId id;
	private Historico historico;
	private Disciplina disciplina;
	private int numNota;
	private int numFalta;

	public HistoricoItem() {
	}

	public HistoricoItem(HistoricoItemId id, Historico historico,
			Disciplina disciplina, int numNota, int numFalta) {
		this.id = id;
		this.historico = historico;
		this.disciplina = disciplina;
		this.numNota = numNota;
		this.numFalta = numFalta;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "indHistorico", column = @Column(name = "ind_historico", nullable = false)),
			@AttributeOverride(name = "indGradeCurricular", column = @Column(name = "ind_grade_curricular", nullable = false)),
			@AttributeOverride(name = "indDisciplina", column = @Column(name = "ind_disciplina", nullable = false)) })
	@NotNull
	public HistoricoItemId getId() {
		return this.id;
	}

	public void setId(HistoricoItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_historico", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Historico getHistorico() {
		return this.historico;
	}

	public void setHistorico(Historico historico) {
		this.historico = historico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_disciplina", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@Column(name = "num_nota", nullable = false)
	@NotNull
	public int getNumNota() {
		return this.numNota;
	}

	public void setNumNota(int numNota) {
		this.numNota = numNota;
	}

	@Column(name = "num_falta", nullable = false)
	@NotNull
	public int getNumFalta() {
		return this.numFalta;
	}

	public void setNumFalta(int numFalta) {
		this.numFalta = numFalta;
	}

}
