package br.inf.prismasoft.academix.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Historico generated by hbm2java
 */
@Entity
@Table(name = "HISTORICO", schema = "ACADEMIX")
public class Historico implements java.io.Serializable {

	private static final long serialVersionUID = -6235792495736359799L;
	private int idtHistorico;
	private Curso curso;
	private Aluno aluno;
	private Set<HistoricoItem> historicoItems = new HashSet<HistoricoItem>(0);

	public Historico() {
	}

	public Historico(int idtHistorico, Curso curso, Aluno aluno) {
		this.idtHistorico = idtHistorico;
		this.curso = curso;
		this.aluno = aluno;
	}

	public Historico(int idtHistorico, Curso curso, Aluno aluno,
			Set<HistoricoItem> historicoItems) {
		this.idtHistorico = idtHistorico;
		this.curso = curso;
		this.aluno = aluno;
		this.historicoItems = historicoItems;
	}

	@Id
	@Column(name = "idt_historico", unique = true, nullable = false)
	@NotNull
	public int getIdtHistorico() {
		return this.idtHistorico;
	}

	public void setIdtHistorico(int idtHistorico) {
		this.idtHistorico = idtHistorico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_curso", nullable = false)
	@NotNull
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_aluno", nullable = false)
	@NotNull
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "historico")
	public Set<HistoricoItem> getHistoricoItems() {
		return this.historicoItems;
	}

	public void setHistoricoItems(Set<HistoricoItem> historicoItems) {
		this.historicoItems = historicoItems;
	}

}
