package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * HistoricoItemId generated by hbm2java
 */
@Embeddable
public class HistoricoItemId implements java.io.Serializable {

	private static final long serialVersionUID = -1916903972845715174L;
	private int indHistorico;
	private int indGradeCurricular;
	private int indDisciplina;

	public HistoricoItemId() {
	}

	public HistoricoItemId(int indHistorico, int indGradeCurricular,
			int indDisciplina) {
		this.indHistorico = indHistorico;
		this.indGradeCurricular = indGradeCurricular;
		this.indDisciplina = indDisciplina;
	}

	@Column(name = "ind_historico", nullable = false)
	@NotNull
	public int getIndHistorico() {
		return this.indHistorico;
	}

	public void setIndHistorico(int indHistorico) {
		this.indHistorico = indHistorico;
	}

	@Column(name = "ind_grade_curricular", nullable = false)
	@NotNull
	public int getIndGradeCurricular() {
		return this.indGradeCurricular;
	}

	public void setIndGradeCurricular(int indGradeCurricular) {
		this.indGradeCurricular = indGradeCurricular;
	}

	@Column(name = "ind_disciplina", nullable = false)
	@NotNull
	public int getIndDisciplina() {
		return this.indDisciplina;
	}

	public void setIndDisciplina(int indDisciplina) {
		this.indDisciplina = indDisciplina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoricoItemId))
			return false;
		HistoricoItemId castOther = (HistoricoItemId) other;

		return (this.getIndHistorico() == castOther.getIndHistorico())
				&& (this.getIndGradeCurricular() == castOther
						.getIndGradeCurricular())
				&& (this.getIndDisciplina() == castOther.getIndDisciplina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIndHistorico();
		result = 37 * result + this.getIndGradeCurricular();
		result = 37 * result + this.getIndDisciplina();
		return result;
	}

}
