package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AvaliacaoItem generated by hbm2java
 */
@Entity
@Table(name = "AVALIACAO_ITEM", schema = "ACADEMIX")
public class AvaliacaoItem  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2846128367968031904L;
	private Integer idtAvaliacaoItem;
     private Avaliacao avaliacao;
     private Aluno aluno;
     private double numNota;

    public AvaliacaoItem() {
    }

    public AvaliacaoItem(Avaliacao avaliacao, Aluno aluno, double numNota) {
       this.avaliacao = avaliacao;
       this.aluno = aluno;
       this.numNota = numNota;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_avaliacao_item", unique=true, nullable=false)
    public Integer getIdtAvaliacaoItem() {
        return this.idtAvaliacaoItem;
    }
    
    public void setIdtAvaliacaoItem(Integer idtAvaliacaoItem) {
        this.idtAvaliacaoItem = idtAvaliacaoItem;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ind_avaliacao", nullable=false)
    @NotNull
    public Avaliacao getAvaliacao() {
        return this.avaliacao;
    }
    
    public void setAvaliacao(Avaliacao avaliacao) {
        this.avaliacao = avaliacao;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ind_aluno", nullable=false)
    @NotNull
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    
    @Column(name="num_nota", nullable=false, precision=2, scale=1)
    @NotNull
    public double getNumNota() {
        return this.numNota;
    }
    
    public void setNumNota(double numNota) {
        this.numNota = numNota;
    }




}


