package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * DiscGradeCurricularId generated by hbm2java
 */
@Embeddable
public class DiscGradeCurricularId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4237830381940394963L;
	private int indGradeCurricular;
	private int indDisciplina;

	public DiscGradeCurricularId() {
	}

	public DiscGradeCurricularId(int indGradeCurricular, int indDisciplina) {
		this.indGradeCurricular = indGradeCurricular;
		this.indDisciplina = indDisciplina;
	}

	@Column(name = "ind_grade_curricular", nullable = false)
	@NotNull
	public int getIndGradeCurricular() {
		return this.indGradeCurricular;
	}

	public void setIndGradeCurricular(int indGradeCurricular) {
		this.indGradeCurricular = indGradeCurricular;
	}

	@Column(name = "ind_disciplina", nullable = false)
	@NotNull
	public int getIndDisciplina() {
		return this.indDisciplina;
	}

	public void setIndDisciplina(int indDisciplina) {
		this.indDisciplina = indDisciplina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiscGradeCurricularId))
			return false;
		DiscGradeCurricularId castOther = (DiscGradeCurricularId) other;

		return (this.getIndGradeCurricular() == castOther
				.getIndGradeCurricular())
				&& (this.getIndDisciplina() == castOther.getIndDisciplina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIndGradeCurricular();
		result = 37 * result + this.getIndDisciplina();
		return result;
	}

}
