package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * DiscGradeCurricular generated by hbm2java
 */
@Entity
@Table(name = "DISC_GRADE_CURRICULAR", schema = "ACADEMIX")
public class DiscGradeCurricular implements java.io.Serializable {

	private static final long serialVersionUID = -8094224226162694641L;
	private Integer idtDiscGradeCurricular;
	private GradeCurricular gradeCurricular;
	private Disciplina disciplina;
	private Integer numCargaHoraria;

	public DiscGradeCurricular() {
	}

	public DiscGradeCurricular(GradeCurricular gradeCurricular,
			Disciplina disciplina) {
		this.gradeCurricular = gradeCurricular;
		this.disciplina = disciplina;
	}

	public DiscGradeCurricular(GradeCurricular gradeCurricular,
			Disciplina disciplina, Integer numCargaHoraria) {
		this.gradeCurricular = gradeCurricular;
		this.disciplina = disciplina;
		this.numCargaHoraria = numCargaHoraria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idt_disc_grade_curricular", unique = true, nullable = false)
	public Integer getIdtDiscGradeCurricular() {
		return this.idtDiscGradeCurricular;
	}

	public void setIdtDiscGradeCurricular(Integer idtDiscGradeCurricular) {
		this.idtDiscGradeCurricular = idtDiscGradeCurricular;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_grade_curricular", nullable = false)
	@NotNull
	public GradeCurricular getGradeCurricular() {
		return this.gradeCurricular;
	}

	public void setGradeCurricular(GradeCurricular gradeCurricular) {
		this.gradeCurricular = gradeCurricular;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_disciplina", nullable = false)
	@NotNull
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@Column(name = "num_carga_horaria")
	public Integer getNumCargaHoraria() {
		return this.numCargaHoraria;
	}

	public void setNumCargaHoraria(Integer numCargaHoraria) {
		this.numCargaHoraria = numCargaHoraria;
	}

}
