package br.inf.prismasoft.academix.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "ENDERECO", schema = "ACADEMIX")
public class Endereco implements java.io.Serializable {

	private static final long serialVersionUID = 36307328932464563L;
	private String idtCep;
	private String desLogradouro;
	private String desBairro;
	private String desCidade;
	private String desUf;
	private Set<Professor> professors = new HashSet<Professor>(0);
	private Set<Campus> campuses = new HashSet<Campus>(0);
	private Set<AlunoEndereco> alunoEnderecos = new HashSet<AlunoEndereco>(0);

	public Endereco() {
	}

	public Endereco(String idtCep, String desLogradouro, String desBairro,
			String desCidade, String desUf) {
		this.idtCep = idtCep;
		this.desLogradouro = desLogradouro;
		this.desBairro = desBairro;
		this.desCidade = desCidade;
		this.desUf = desUf;
	}

	public Endereco(String idtCep, String desLogradouro, String desBairro,
			String desCidade, String desUf, Set<Professor> professors,
			Set<Campus> campuses, Set<AlunoEndereco> alunoEnderecos) {
		this.idtCep = idtCep;
		this.desLogradouro = desLogradouro;
		this.desBairro = desBairro;
		this.desCidade = desCidade;
		this.desUf = desUf;
		this.professors = professors;
		this.campuses = campuses;
		this.alunoEnderecos = alunoEnderecos;
	}

	@Id
	@Column(name = "idt_cep", unique = true, nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getIdtCep() {
		return this.idtCep;
	}

	public void setIdtCep(String idtCep) {
		this.idtCep = idtCep;
	}

	@Column(name = "des_logradouro", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDesLogradouro() {
		return this.desLogradouro;
	}

	public void setDesLogradouro(String desLogradouro) {
		this.desLogradouro = desLogradouro;
	}

	@Column(name = "des_bairro", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getDesBairro() {
		return this.desBairro;
	}

	public void setDesBairro(String desBairro) {
		this.desBairro = desBairro;
	}

	@Column(name = "des_cidade", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getDesCidade() {
		return this.desCidade;
	}

	public void setDesCidade(String desCidade) {
		this.desCidade = desCidade;
	}

	@Column(name = "des_uf", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDesUf() {
		return this.desUf;
	}

	public void setDesUf(String desUf) {
		this.desUf = desUf;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Professor> getProfessors() {
		return this.professors;
	}

	public void setProfessors(Set<Professor> professors) {
		this.professors = professors;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Campus> getCampuses() {
		return this.campuses;
	}

	public void setCampuses(Set<Campus> campuses) {
		this.campuses = campuses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<AlunoEndereco> getAlunoEnderecos() {
		return this.alunoEnderecos;
	}

	public void setAlunoEnderecos(Set<AlunoEndereco> alunoEnderecos) {
		this.alunoEnderecos = alunoEnderecos;
	}

}
