package br.inf.prismasoft.academix.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * FaltaItem generated by hbm2java
 */
@Entity
@Table(name = "FALTA_ITEM", schema = "ACADEMIX")
public class FaltaItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4041767953050014459L;
	private Integer idtFaltaItem;
	private Aluno aluno;
	private Falta falta;
	private int numQtdFalta;

	public FaltaItem() {
	}

	public FaltaItem(Aluno aluno, Falta falta, int numQtdFalta) {
		this.aluno = aluno;
		this.falta = falta;
		this.numQtdFalta = numQtdFalta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idt_falta_item", unique = true, nullable = false)
	public Integer getIdtFaltaItem() {
		return this.idtFaltaItem;
	}

	public void setIdtFaltaItem(Integer idtFaltaItem) {
		this.idtFaltaItem = idtFaltaItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_aluno", nullable = false)
	@NotNull
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_falta", nullable = false)
	@NotNull
	public Falta getFalta() {
		return this.falta;
	}

	public void setFalta(Falta falta) {
		this.falta = falta;
	}

	@Column(name = "num_qtd_falta", nullable = false)
	@NotNull
	public int getNumQtdFalta() {
		return this.numQtdFalta;
	}

	public void setNumQtdFalta(int numQtdFalta) {
		this.numQtdFalta = numQtdFalta;
	}

}
